language: java
jdk:
  - openjdk8
sudo: false
cache:
  directories:
    - "$HOME/.m2"
notifications:
  email: false
install:
  - mvn -nsu -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} clean deploy
before_deploy:
  - echo '|1|DBFhltHRAVmrfmMZPLbN7FwnS5E=|79CP65+tOIeVNeNNC2R680mpV9o= ecdsa-sha2-nistp256
    AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBK/krqsEUrVoDrYIc7I7nsiSCF0M7Xxr379IqZ2pLUPlxF2Or/MkTTokXzRsyspJazL1W1UrBDmKXHfO6+tyMMw='
    >> $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_989a381f1379_key -iv $encrypted_989a381f1379_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - chmod +x scripts/deploy-staging.sh
  - chmod +x scripts/deploy-release.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy-staging.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy-release.sh
    on:
      tags: true
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh failure $WEBHOOK_URL"
